### ISSUE TITLE
Mail Directory's Purpose

### ISSUE THREAD

**Issue by Coder206** [aaronprisk/corvos-site#3]
The `mail` directory has a template `php` [page](https://github.com/aaronprisk/corvos-site/blob/master/mail/contact_me.php) with default values. I was wondering about its purpose, it does not seem to be useful for the operation of the site.

**Comment by aaronprisk** [comment]
Agreed. Looks like it was a left over from the bootstrap template I used initially. I'll go ahead and remove it.
